# Generated by Django 5.0.1 on 2024-01-29 11:15

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_categories_tag_article_commentary_subarticle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='partners',
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Telefon raqamini 901234567 formatida kiriting.', max_length=128, null=True, region='UZ'),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article/partners/')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='main.aboutme')),
            ],
        ),
    ]
