# Generated by Django 5.0.1 on 2024-01-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutme_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='top_level_comment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
