# Generated by Django 5.0.1 on 2024-01-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
