# Generated by Django 5.0.1 on 2024-01-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_services_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'top'), (1, 'low')])),
                ('name', models.CharField(max_length=225)),
                ('last_week', models.IntegerField()),
                ('last_month', models.IntegerField()),
                ('percent', models.IntegerField()),
            ],
        ),
    ]
