# Generated by Django 5.0.1 on 2024-02-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='awards_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='happy_customers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='project_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
